spring:
  profiles:
    active:
      - local
server:
  baseUrl: http://localhost:3000/
  imageUrl: images/
  imageServerDir: c:/images/luckhana/
---
spring:
  profiles: local
server:
  baseUrl: http://localhost:8080/
  imageUrl: luckhana/images/
  imageServerDir: c:/images/luckhana/
---